---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_bags_path: test/fixtures/data_bags
  roles_path: test/fixtures/roles
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-7

suites:
  - name: fqdn
    run_list:
      - recipe[feature_switch_fqdn::default]
    verifier:
      inspec_tests:
        - test/integration/feature_switch_fqdn
  - name: role
    run_list:
      - role[janitor]
      - role[builder]
    verifier:
      inspec_tests:
        - test/integration/feature_switch_role
